[package]
name = "bath-hack-25"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
env_logger = "0.11.8"
pollster = "0.4.0"
wgpu = { version = "24.0.3", features = ["vulkan-portability"] }
winit = "0.30.9"
